---
title: "Breast Cancer Project"
output: pdf_document
date: "2024-01-31"
---

# Introduction

# Dataset
```{r libraries}
library(matrixStats)
library(tidyverse)
library(caret)
library(dslabs)
library(knitr)
library(GGally)
```

```{r}
data(brca)
brca <- data.frame(brca$x, y = brca$y) %>% tibble()
glimpse(brca)
```

# Pre-processing
```{r}
set.seed(2024)
test_idx <- createDataPartition(brca$y, times = 1, p = 0.2, list = F)
train <- brca[-test_idx, ]
test <- brca[test_idx, ]
p <- ncol(brca)
train[,1:(p-1)] <- apply(train[,1:(p-1)], 2,
                                   function(x) scale(x))
test[,1:(p-1)] <- apply(test[,1:(p-1)], 2,
                                   function(x) scale(x))

```

# Descriptive Analysis
```{r}
my_image <- function(x, zlim = range(x), ...){
  colors = rev(RColorBrewer::brewer.pal(9, "RdBu"))
  cols <- 1:ncol(x)
  rows <- 1:nrow(x)
  image(cols, rows, t(x[rev(rows),,drop=FALSE]), xaxt = "n", yaxt = "n",
        xlab="", ylab="",  col = colors, zlim = zlim, ...)
  abline(h=rows + 0.5, v = cols + 0.5)
  axis(side = 1, cols, colnames(x), las = 2)
}

my_image(cor(train[, 1:(p-1)]))
```

```{r}
kable(cor(train[, 1:(p-1)]))
```

```{r}
train %>% pivot_longer(cols = 1:(p-1), names_to = "col",
                       values_to = "value") %>% 
  mutate(col = factor(col),
         idx = factor(as.numeric(col)%/%3)) %>% 
  ggplot(aes(x = factor(col), y = value, fill = y))+
  geom_boxplot()+
  facet_wrap(~idx, scales = "free")
```

# Adjusting models
```{r}
models <- c("glm", "lda", "naive_bayes", "knn", "gamLoess", "qda", "rf")
train(y ~ ., data = train, method = "glm", )
```

